#!/bin/bash

break_debug=1
logfile='test.log'
img='floppy.img'
raw='floppy.raw'
dd_bs=1024
normal_size=$((1024*256))
floppy_size=1024
current_dir=`pwd`
ptldir="../src"

ptlchkimg=$ptldir/partclone.chkimg
ptlrestore=$ptldir/partclone.restore

mkfs_option_for_ext2='-F'
mkfs_option_for_ext3='-F'
mkfs_option_for_ext4='-F'
mkfs_option_for_reiserfs='-f'
mkfs_option_for_ntfs='-f -F'

_ptlbreak(){
    if [ $break_debug -ne 0 ];then

	echo "continue test process(Y/n)? default yes"
	read con
	if [ "$con" == "n" ];then
	    exit 1
	fi
    fi

}

_findmkfs(){
    fs=$1
    mkfs_path=$(locate mkfs.$fs|grep sbin)
    if [ -z $mkfs_path ]; then
	echo  >&2 "can't find mkfs.$fs"
	exit 1
    fi
    echo $mkfs_path

}

_ptlname(){
    fs=$1
    case "$fs" in
	ext2|ext3|ext4|extfs)
	    ptl="$ptldir/partclone.extfs"
	;;
	fat16|fat12|fat32|fat|vfat)
	    ptl="$ptldir/partclone.vfat"
	;;
	*)
	    ptl="$ptldir/partclone.$fs"
    esac

    if [ ! -f $ptl ]; then
	echo >&2 "can't find $ptl"
	exit 1
    fi
    echo "$ptl"
}
