#!/bin/bash

. _common
break_debug=0
manual_fs=$1

test_fs=$formatable_fs
dd_count=$normal_size
[ -z $manual_fs ] || test_fs=$manual_fs

source_partition="/dev/sdb1"
target_partition="/dev/sdc1"
source_mountpoint="/test/source"
target_mountpoint="/test/target"
data_pool="/test/datapool/"
chfile="/test/checksum.log"
cchfile="/test/checksum_test.log"

#main
for fs in $test_fs; do
    echo "go $fs test"
    mkdir -p $source_mountpoint $target_mountpoint $data_pool
    umount $target_mountpoint $source_mountpoint
    set -e
    ptlfs=$(_ptlname $fs)
    mkfs=$(_findmkfs $fs)
    logfile="/test/clone-$fs.log"

    echo "format $source_partition as $fs partition"
    echo "mkfs.$fs `eval echo "$"mkfs_option_for_$fs""` $source_partition"
    _ptlbreak
    $mkfs `eval echo "$"mkfs_option_for_$fs""` $source_partition
    _check_return_code

    echo "prepare data to clone"
    _ptlbreak
    mount -t $fs $source_partition $source_mountpoint
    set +e 
    # rsync error while rsync to vfat
    # rsync error while rsync to exfat
    # rsync -arl $data_pool $source_mountpoint 
    # use cp -r
    cp -r $data_pool/* $source_mountpoint
    set -e
    sync
    pushd $source_mountpoint
    find . -type f -exec md5sum '{}' \; > $chfile
    popd
    umount $source_mountpoint
    echo "md5sum done"

    echo "device to device clone, $source_partition to $target_partition"
    echo "$ptlfs -d -b -s $source_partition -o $target_partition -L $logfile"
    _ptlbreak
    $ptlfs -q -d -b -s $source_partition -o $target_partition -L $logfile
    _check_return_code

    echo "check data"
    _ptlbreak
    mount -t $fs $target_partition $target_mountpoint
    pushd $target_mountpoint
    md5sum --quiet -c $chfile 2>&1 > $cchfile
    popd
    umount $target_mountpoint
    echo "done"
    _check_return_code

    echo "$fs test ok"
    echo "clear tmp files"
    _ptlbreak
    set +e
    umount $target_mountpoint $source_mountpoint
    rm -r $target_mountpoint $source_mountpoint $logfile $chfile $cchfile
    _check_return_code

done
echo "Finish!"
