Document: partclone
Title: Debian partclone Manual
Author: <insert document author here>
Abstract: This manual describes what partclone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/partclone/partclone.sgml.gz

Format: postscript
Files: /usr/share/doc/partclone/partclone.ps.gz

Format: text
Files: /usr/share/doc/partclone/partclone.text.gz

Format: HTML
Index: /usr/share/doc/partclone/html/index.html
Files: /usr/share/doc/partclone/html/*.html

  
