.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MOTION-CONTROL 1 "June, 2004"
.SH NAME
motion-control \- Controlling Motion via xml-rpc
.SH SYNOPSIS
.B motion-control
.SH DESCRIPTION
This manual page documents briefly motion-control.

Since version 3.1.12 Motion comes with a new exciting feature which is the
ability to control Motion while it is running.

This means that Motion now has a built in http server called xmlrpc-httpd.
This listens on a port specified by the new 'control_port' config file option.
The control protocol is called xml-rpc. It is the job of motion-control to
control these new control features of Motion.

See section "Controlling Motion via xml-rpc" in
/usr/share/doc/motion/motion_guide.html for further information.

This manual page was written for the Debian distribution because the original
program does not have a manual page.
.PP
.SH AUTHORS
Jeroen Vreeken (pe1rxq@amsat.org),
Folkert van Heusden,
Kenneth Lavrsen (kenneth@lavrsen.dk)
.P
This minimal manual page was written by Frederik Dannemare <frederik@dannemare.net>
for the Debian project.
