/* DO NOT EDIT THIS FILE - IT IS REGENERATED AT EVERY COMPILE -
 * IT GIVES BETTER TRACKING OF DEVELOPMENT VERSIONS
 * WHETHER THEY ARE BUILT BY OTHERS OR DURING DEVELOPMENT OR FOR THE
 * OFFICIAL PARTCLONE RELEASES.
 */
<<<<<<< HEAD
<<<<<<< HEAD
#define git_version  "1faf626392ba4f4ee89cea86b59b6e595a4c04c4"
=======
#define git_version  "a9cb7ab754935210cd1bddfd17b5c5fb7ac85115"
>>>>>>> c5651a8... fix segfault for info.c
=======
#define git_version  "53a8038a1bb57d0f384e2e8378a68089bd9f04d4"
>>>>>>> a9f7045... finish tests script

