name: Manual workflow on my host
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: | 
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get build-dep -y partclone
          sudo apt-get install -y f2fs-tools hfsprogs exfatprogs gddrescue libfuse-dev jfsutils reiser4progs hfsprogs hfsplus reiserfsprogs
    - name: automake
      run: ./autogen
    - name: configure
      run: ./configure --enable-fs-test --enable-feature-test --enable-extfs --enable-ntfs --enable-fat --enable-exfat --enable-hfsp --enable-apfs --enable-btrfs --enable-minix --enable-f2fs --enable-reiser4 --enable-xfs --enable-nilfs2 --enable-fuse
    - name: make
      run: make
    - name: makeTest
      run: make check
  specialFeatureTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: fuse Test
      if: always()
      run: cd tests && sudo ./imgfuse.test && cd ../ && pwd
    - name: offset Test
      if: always()
      run: cd tests && sudo ./offset.test && cd ../ && pwd
    - name: direct io Test
      if: always()
      run: cd tests && sudo ./direct_io.test && cd ../ && pwd
  BTRFSDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: btrfs Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test btrfs && cd ../ && pwd
  F2FSDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: f2fs Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test f2fs && cd ../ && pwd
  NILFSDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: nilfs2 Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test nilfs2 && cd ../ && pwd
  HFSPDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: hfsplus Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test hfsplus && cd ../ && pwd
  XFSDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: xfs Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test xfs && cd ../ && pwd
  EXT2DataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: ext2 Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test ext2 && cd ../ && pwd
  EXT3DataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: ext3 Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test ext3 && cd ../ && pwd
  EXT4DataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: ext4 Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test ext4 && cd ../ && pwd
  VFATDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: vfat Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test vfat && cd ../ && pwd
  EXFATDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: exfat Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test exfat && cd ../ && pwd
  NTFSDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: ntfs Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test ntfs && cd ../ && pwd 
  MINIXDataIOTest:
    runs-on: self-hosted
    needs: build
    steps:
    - name: minix Data Test
      if: always()
      run: cd tests && sudo env SOURCEPART="/dev/vdb1" env TARGETPART="/dev/vdb2"  bash -x ./data_clone_restore_test minix && cd ../ && pwd

